-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "rentEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "rentPrice" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "rentStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "rentType" TEXT NOT NULL DEFAULT 'per hr.';
